name: Crawler trial trigger

on:
  pull_request:
    paths:
      - "crawler.py"
      - ".github/workflows/**/*.yml"


jobs:
  trial-on-pr:
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        crawling-method: [ "1", "2" ]
    uses: ./.github/workflows/crawler-trial-workflow.yml
    with:
      maximum-requests: "2"
      crawling-method: ${{ matrix.crawling-method }}
      start-spot: "7659cedb-c9c1-4f28-b966-19823fd8666b"
